### PR TITLE
Removed Pending exchange.

### PR DESCRIPTION
**Pull request by ohcee**
We should either be **_On_** an exchange or **_NOT ON_** an exchange.

### CODE REVIEW

**Review by seanPhill — CHANGES_REQUESTED** [review]
NCE has taken an unacceptably long time to complete the listing, so it's reasonable to remove them now, but also while doing this change we may as well remove mention of Graviex, as that delisting happened a long time ago and no opportunity would remain for any further withdrawals.

**Review by seanPhill — CHANGES_REQUESTED** [review]
I would like the new lines 21 to 24 to be something like this. (I can't push to your PR.) You can see that this removes the removed or non-functional exchanges list too, but retains the skeleton of the list in a block comment so that in the future if there is a problem with an exchange we can put them there to give people details of the problem.
```
<!-- <p>———Exchanges recently removed or non-functional———</p>
<ul>
<li></li>
</ul> -->
```

**Comment by ohcee** [comment]
You should be able to push to it now. For some reason the *Allow edits by maintainers* was not checked.

**Review by seanPhill — APPROVED** [review]
All good. It will be a bit cleaner now.

**Pull request merged**
