### PR TITLE
Blog post and news

### PR DESCRIPTION
**Pull request by seanPhill**
Information about NonKYC exchange, the new Veil light wallet, and other things.

### CODE REVIEW

**Review by ohcee — COMMENTED** [review]
Good update. It explains the areas most people are concerned with. Maybe mentioning the faucet would be good also. I don' t think it has been mentioned in any other blogs or news.

**Review by ohcee — CHANGES_REQUESTED** [review]
Side note: I haven't and I don't think Ivan has a working macOS version but Linux, IOS, windows, and android work as far as I'm aware. I have tested Linux and IOS myself.

**Comment by seanPhill** [comment]
> Side note: I haven't and I don't think Ivan has a working macOS version but Linux, IOS, windows, and android work as far as I'm aware. I have tested Linux and IOS myself.

I heard that Ivan was able to get an updated macOS running on an ancient Mac, either a MacBook or Mac Mini, I think, through a third party project that overcomes technicalities that normally prevent unsupported Macs from upgrading, so I think it is working. Let's see if anyone reports any problem running the macOS light wallet.

**Comment by seanPhill** [comment]
A well-needed blog update!

**Pull request merged**
